### ISSUE TITLE
JSON body comes empty

### ISSUE THREAD

**Issue by aruizca** [grails-plugins/grails-rest-client-builder#37]
Trying to reach my REST endpoint the `request.JSON` is empty after executing this:

```
        RestResponse response = rest.get("http://localhost:8080/${grailsApplication.metadata.'app.name'}/ws/question") {
            json([
                occurrenceId: 'f6f8a9b8-4d52-49c3-9352-155f154fc96c',
                userId: userKeef.alaUserId,
                tags: 'octopus, orange',
                comment: 'whatever'
            ])
        }
```

**Comment by aruizca** [comment]
It worked with a post. Can someone tell me why please?

**Comment by graemerocher** [comment]
Currently GET requests do not support a message body

**Comment by aruizca** [comment]
You mean because it is not implemented in this plugin, right?

**Comment by abobwhite** [comment]
@aruizca I believe that's what he meant...because that's the standard. Just because you CAN put a body on GET request doesn't mean you should. 

http://stackoverflow.com/a/983458/1721440
