### ISSUE TITLE
Not able to import RestBuilder

### ISSUE THREAD

**Issue by kastone** [grails-plugins/grails-rest-client-builder#46]
Hello,
We are using Grails 2.4.5 and are trying to use the RestBuilder class to implement some functional tests for our REST API's.
I have included compile "org.grails.plugins:rest-client-builder:2.1.1" in the BuildConfig.groovy file.
I can see that the plugin is downloaded but do not see the RestBuilder class in any src directory. I also do not see any references to other dependencies that might include RestBuilder.
<img width="579" alt="screen shot 2016-05-26 at 12 26 20 pm" src="https://cloud.githubusercontent.com/assets/2530576/15582223/d6738362-233d-11e6-8900-95fc4d94d773.png">

Could this be an issue when the plugin was upgraded/moved for Grails 3.x?
Thanks,
Kathy

**Comment by graemerocher** [comment]
For questions please try Slack (http://slack-signup.grails.org)  or StackOverflow (http://stackoverflow.com/tags/grails)
